<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MSI" failures="1" tests="1" name="EndToEndTest" time="0.057" errors="0" timestamp="2025-09-08T13:40:27 IST">
  <testcase classname="com.saucedemo.tests.MainTest" name="fullEndToEndFlow" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.io.FileNotFoundException: C:\Users\ronyd\git\capstone-project\src\test\resources\Testdata\login.xlsx (The system cannot find the path specified)">
      <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: C:\Users\ronyd\git\capstone-project\src\test\resources\Testdata\login.xlsx (The system cannot find the path specified)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
Caused by: java.io.FileNotFoundException: C:\Users\ronyd\git\capstone-project\src\test\resources\Testdata\login.xlsx (The system cannot find the path specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:159)
at com.saucedemo.utilities.ExcelUtilities.getData(ExcelUtilities.java:13)
at com.saucedemo.tests.MainTest.loginData(MainTest.java:44)
... 25 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- fullEndToEndFlow -->
</testsuite> <!-- EndToEndTest -->
